### ISSUE TITLE
Why am I on the black list? Who gives you the right to judge others?

### ISSUE THREAD

**Issue by JimChengLin** [CleanGithub/blacklist#1]
I clearly remember that
1. I didn't open any issue in https://github.com/ry/deno
So what? Is it a sin to comment?
2. I commented twice. None of them violated the community rules. 
The first one was "we mean no offense, it's just a joke". The second one was "这评论还能动态刷新, 建议知乎学习下, 6666".
Could you tell me what is wrong with me? I was just surprised that GitHub can do real-time comment refreshing.

Who did I harm? It is so crazy! The only authority who can ban others is GitHub. You just have no right to do it! I am considering it as insult to my reputation.

Be a good guy and delete my account, JimChengLin, from the list.

**Comment by molingyu** [comment]
#2
