### ISSUE TITLE
i said "lock this plz" then you add me to the blacklist?

### ISSUE THREAD

**Issue by Kingwl** [CleanGithub/blacklist#2]
You don't have the permission to do this because you can't make sure that your statistics are correct

**Comment by SilverRainZ** [comment]
This is issue of Github, you just lead to another cyber violence.

**Comment by molingyu** [comment]
@SilverRainZ  谢谢你的回复。实际上这个repo的第一个issues还没写下的时候，我就已经决定放弃我最开始的想法了——用 bot 将这些人 扳掉。
这个 repo 本身存在的问题也很多，比如边界，比如过于粗暴的level分类（5/10）。
但我不会去从删掉哪一位。【首先一旦我开始删掉某个人，有更多的人会要求我从列表上把他们删掉】

我现在正在写知乎那边的回答。之后我会给一份更详细的回复。希望谅解。
@Kingwl 
@JimChengLin

p.s. 从本意上，我十分不希望这个项目被正真使用起来。

**Comment by AngryPowman** [comment]
I thought the list is unfair and it would be senseless because it doesn't have definitions to judge whether such behaviors were wrong.

**Comment by Kingwl** [comment]
is that mean we should report this repo?

**Comment by molingyu** [comment]
@Kingwl 我会在之后删掉它 如果你觉得我们之间存在信任的话

**Comment by Kingwl** [comment]
you can do everything you want, the same as the man that open garbage issue
